### PR TITLE
Raise ArgumentError for invalid mail text

### LINKED ISSUE #21: Consider invalid format email
As of version 0.5.0, `get_domain` method is implemented like this:

```ruby
  def self.get_domain(email)
    email.split('@').last.downcase.strip
  end
```

However, it can return wrong domain or raise error for invalid inputs:

```ruby
Freemail.get_domain('apple.com@') #=> "apple.com"
Freemail.get_domain('@') #=> undefined method `downcase' for nil:NilClass (NoMethodError)
```

It should raise ArgumentError:

```ruby
Freemail.get_domain('apple.com@') #=> ArgumentError
Freemail.get_domain('@') #=> ArgumentError
```

Or probably should return empty value (or nil):

```ruby
Freemail.get_domain('apple.com@') #=> ""
Freemail.get_domain('@') #=> ""
```

### PR DESCRIPTION
**Pull request by JunichiIto**
Fix https://github.com/smudge/freemail/issues/21

### CODE REVIEW

File: spec/freemail_spec.rb [hunk 1]
```diff
@@ -22,6 +22,36 @@
       let(:email) { 'steve@apple.com' }
       it { is_expected.to be(false) }
     end
+
+    context 'with a user-name-only email' do
+      let(:email) { 'apple.com@' }
+      it { expect { subject }.to raise_error(ArgumentError, /Invalid email/) }
```
Comment (JunichiIto) [inline spec/freemail_spec.rb]: It might be okay if it returns true or false value:

```ruby
# maybe true
it { is_expected.to be(true) }

# or maybe false
it { is_expected.to be(false) }
```

But I'm not sure which is desirable result.

Comment (smudge) [reply spec/freemail_spec.rb]: Good point! The answer may depend on whether it is paired with a separate validation in the consuming code.

I'm thinking that maybe it could act like `String#to_i` or another such type-cast/value-transform method, where an invalid string will still produce some output (e.g. `'asdf'.to_i => 0`) and it's on the developer to validate the inputs. In a Rails context, it's common for ActiveModel::Validations to do the heavy lifting, and email validation is complex enough that I think it would make sense for this library to avoid having an opinion about what constitutes a "valid email" and avoid raising exceptions.

File: lib/freemail.rb [hunk 2]
```diff
@@ -28,6 +28,11 @@ def self.free_or_disposable?(email)
   end
 
   def self.get_domain(email)
-    email.split('@').last.downcase.strip
+    parts = email.split('@').map { |s| s.downcase.strip }
+    if parts.size == 2 && parts.none?(&:empty?)
+      parts.last
+    else
+      raise ArgumentError, "Invalid email: #{email}"
+    end
```
Comment (smudge) [inline lib/freemail.rb]: This will split at the first '@' and return everything afterwards (including subsequent @s) and should pass the `gmail.com@` test by returning `''` and not considering that a "free" email.

```suggestion
    email.split('@')[1..-1].join('@')&.downcase&.strip
```

File: spec/freemail_spec.rb [hunk 3]
```diff
@@ -22,6 +22,36 @@
...
+
+    context 'with a blank text' do
+      let(:email) { '' }
+      it { expect { subject }.to raise_error(ArgumentError, /Invalid email/) }
+    end
+
+    context 'with a double-@ email' do
+      let(:email) { 'gopackers@@gmail.com' }
+      it { expect { subject }.to raise_error(ArgumentError, /Invalid email/) }
+    end
```
Comment (smudge) [inline spec/freemail_spec.rb]:
```suggestion
    context 'with a user-name-only email' do
      let(:email) { 'gmail.com@' }
      it { is_expected.to be(false) }
    end

    context 'with a domain-only email' do
      let(:email) { '@gmail.com' }
      it { is_expected.to be(true) }
    end

    context 'with an @-only email' do
      let(:email) { '@' }
      it { is_expected.to be(false) }
    end

    context 'with an empty string' do
      let(:email) { '' }
      it { is_expected.to be(false) }
    end

    context 'with a double-@ email' do
      let(:email) { 'gopackers@@gmail.com' }
      it { is_expected.to be(false) }
    end
```

File: spec/freemail_spec.rb [hunk 4]
```diff
@@ -41,6 +66,36 @@
...
```
Comment (smudge) [inline spec/freemail_spec.rb]:
```suggestion
    context 'with a user-name-only email' do
      let(:email) { '10minutemail.com@' }
      it { is_expected.to be(false) }
    end

    context 'with a domain-only email' do
      let(:email) { '@10minutemail.com' }
      it { is_expected.to be(true) }
    end

    context 'with a double-@ email' do
      let(:email) { 'gopackers@@10minutemail.com' }
      it { is_expected.to be(false) }
    end
```

File: spec/freemail_spec.rb [hunk 5]
```diff
@@ -60,6 +100,36 @@
...
```
Comment (smudge) [inline spec/freemail_spec.rb]:
```suggestion
```
